### ISSUE TITLE
Minor cosmetic issue: missing new line

### ISSUE THREAD

**Issue by valiko-ua** [newren/git-filter-repo#84]
New line (or comma) is missing after `Parsed 174 commits`:

```Shell
$ git filter-repo --mailmap /c/gitrepos/my_mail_map.txt
Parsed 174 commitsHEAD is now at 55a63cb XXXXXXXXXX
Enumerating objects: 3637, done.
Counting objects: 100% (3637/3637), done.
Delta compression using up to 4 threads
Compressing objects: 100% (1532/1532), done.
Writing objects: 100% (3637/3637), done.
Total 3637 (delta 2058), reused 3569 (delta 2058), pack-reused 0

New history written in 1.11 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
Completely finished after 2.88 seconds.
```

**Comment by newren** [comment]
Indeed; it would often print the newline there, but there was a race condition causing it to sometimes be missed.  I pushed up a commit to fix this.

Thanks for the report!

**Comment by akmalick** [comment]
I have the latest script, d760d24 (at the time of writing this comment).
I can see the issue is still there. In my case :

```
$ git filter-repo --invert-paths --path README.md
Parsed 3 commitsHEAD is now at bd02638 Delete CODEOWNERS
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (6/6), done.
Total 6 (delta 0), reused 2 (delta 0), pack-reused 0

New history written in 0.29 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
Completely finished after 0.61 seconds.
```

**Comment by newren** [comment]
@akmalick : does the following patch fix the issue for you?

```
diff --git a/git-filter-repo b/git-filter-repo
index 4c7a2c3..b6d8f0e 100755
--- a/git-filter-repo
+++ b/git-filter-repo
@@ -343,6 +343,7 @@ class ProgressWriter(object):
     if self._last_message:
       self.show(self._last_message)
     sys.stdout.write("\n")
+    sys.stdout.flush()
 
 class _IDs(object):
   """
```
